name: Terraform GCP

on:
  pull_request:
  push:
    branches:
      - main



jobs:
  # JOB 1: Initialization
  terraform-init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SA_KEY }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: |
          cd ./compute
          terraform init

  # JOB 2: Plan (Runs after Init)
  terraform-plan:
    runs-on: ubuntu-latest
    needs: terraform-init
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SA_KEY }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: cd ./compute && terraform init
      - name: Terraform Plan
        run: cd ./compute && terraform plan -no-color

  # JOB 3: Apply (Runs after Plan, only on Merge/Push)
  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SA_KEY }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: cd ./compute && terraform init
      - name: Terraform Apply
        run: cd ./compute && terraform apply -auto-approve
      - name: Destroy
        run: cd ./compute && terraform init && terraform destroy -auto-approve

 
