name: Terraform GCP CI/CD

on:
  pull_request:
    branches: [ main ]

  push:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      action:
        description: "Choose action: apply or destroy"
        required: true
        default: "apply"
      confirm_destroy:
        description: "Type YES to confirm destroy"
        required: false

jobs:

  terraform-init:
    name: "1. Init"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SA_KEY }}

      - uses: hashicorp/setup-terraform@v3

      - name: Init
        run: cd ./compute && terraform init

  terraform-plan:
    name: "2. Plan"
    needs: terraform-init
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SA_KEY }}

      - uses: hashicorp/setup-terraform@v3

      - name: Plan
        run: cd ./compute && terraform init && terraform plan -no-color

  terraform-apply:
    name: "3. Apply"
    needs: terraform-plan

    # Auto apply only on push to main OR manual apply
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply')

    runs-on: ubuntu-latest

    # 🔐 Manual approval required
    environment:
      name: production

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SA_KEY }}

      - uses: hashicorp/setup-terraform@v3

      - name: Apply
        run: cd ./compute && terraform init && terraform apply -auto-approve

  terraform-destroy:
    name: "4. Destroy"

    # Only manual trigger + explicit confirmation
    if: |
      github.event_name == 'workflow_dispatch' &&
      github.event.inputs.action == 'destroy' &&
      github.event.inputs.confirm_destroy == 'YES'

    runs-on: ubuntu-latest

    # 🔐 Manual approval required
    environment:
      name: production

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SA_KEY }}

      - uses: hashicorp/setup-terraform@v3

      - name: Destroy
        run: cd ./compute && terraform init && terraform destroy -auto-approve
