name: Terraform GCP

on:
  pull_request:
  push:
    branches:
      - main



jobs:
  terraform:
    runs-on: ubuntu-latest



    steps:  
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: Authenticate to Google Cloud (Service Account Key)
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SA_KEY }}
    
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
         cd ./compute
         terraform init

      - name: Terraform Validate
        run: |
         cd ./compute
         terraform validate

      - name: Terraform Plan
        run: |
         cd ./compute
         terraform plan -no-color
